Repository haiiliin/pyqtribbon, pull requests merged in 2023-04, with the labels that each got.

#54 可以通过拖动 RibbonTitleWidget 实现窗口移动
  pyqtribbon/titlewidget.py
Labels: enhancement, minor

#55 Fix title widget events
  pyqtribbon/__init__.py
  pyqtribbon/logger.py
  pyqtribbon/titlewidget.py
Labels: bug

#61 Test title widget mouse events
  .github/release-drafter.yml
  .gitignore
  pyproject.toml
  pyqtribbon/titlewidget.py
  tests/test_titlewidget.py
  tox.ini
Labels: test

#62 Remove tox coveralls env
  tox.ini
Labels: test
